// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: debs2015.proto

package de.tum.i13.pb;

public final class Debs2015Protos {
  private Debs2015Protos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TaxitripOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pb.Taxitrip)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string medallion = 1;</code>
     */
    boolean hasMedallion();
    /**
     * <code>required string medallion = 1;</code>
     */
    java.lang.String getMedallion();
    /**
     * <code>required string medallion = 1;</code>
     */
    com.google.protobuf.ByteString
        getMedallionBytes();

    /**
     * <code>required string hack_license = 2;</code>
     */
    boolean hasHackLicense();
    /**
     * <code>required string hack_license = 2;</code>
     */
    java.lang.String getHackLicense();
    /**
     * <code>required string hack_license = 2;</code>
     */
    com.google.protobuf.ByteString
        getHackLicenseBytes();

    /**
     * <code>required string pickup_datetime = 3;</code>
     */
    boolean hasPickupDatetime();
    /**
     * <code>required string pickup_datetime = 3;</code>
     */
    java.lang.String getPickupDatetime();
    /**
     * <code>required string pickup_datetime = 3;</code>
     */
    com.google.protobuf.ByteString
        getPickupDatetimeBytes();

    /**
     * <code>required string dropoff_datetime = 4;</code>
     */
    boolean hasDropoffDatetime();
    /**
     * <code>required string dropoff_datetime = 4;</code>
     */
    java.lang.String getDropoffDatetime();
    /**
     * <code>required string dropoff_datetime = 4;</code>
     */
    com.google.protobuf.ByteString
        getDropoffDatetimeBytes();

    /**
     * <code>required uint32 trip_time_in_secs = 5;</code>
     */
    boolean hasTripTimeInSecs();
    /**
     * <code>required uint32 trip_time_in_secs = 5;</code>
     */
    int getTripTimeInSecs();

    /**
     * <code>required float trip_distance = 6;</code>
     */
    boolean hasTripDistance();
    /**
     * <code>required float trip_distance = 6;</code>
     */
    float getTripDistance();

    /**
     * <code>required float pickup_longitude = 7;</code>
     */
    boolean hasPickupLongitude();
    /**
     * <code>required float pickup_longitude = 7;</code>
     */
    float getPickupLongitude();

    /**
     * <code>required float pickup_latitude = 8;</code>
     */
    boolean hasPickupLatitude();
    /**
     * <code>required float pickup_latitude = 8;</code>
     */
    float getPickupLatitude();

    /**
     * <code>required float dropoff_longitude = 9;</code>
     */
    boolean hasDropoffLongitude();
    /**
     * <code>required float dropoff_longitude = 9;</code>
     */
    float getDropoffLongitude();

    /**
     * <code>required float dropoff_latitude = 10;</code>
     */
    boolean hasDropoffLatitude();
    /**
     * <code>required float dropoff_latitude = 10;</code>
     */
    float getDropoffLatitude();

    /**
     * <code>required string payment_type = 11;</code>
     */
    boolean hasPaymentType();
    /**
     * <code>required string payment_type = 11;</code>
     */
    java.lang.String getPaymentType();
    /**
     * <code>required string payment_type = 11;</code>
     */
    com.google.protobuf.ByteString
        getPaymentTypeBytes();

    /**
     * <code>required float fare_amount = 12;</code>
     */
    boolean hasFareAmount();
    /**
     * <code>required float fare_amount = 12;</code>
     */
    float getFareAmount();

    /**
     * <code>required float surcharge = 13;</code>
     */
    boolean hasSurcharge();
    /**
     * <code>required float surcharge = 13;</code>
     */
    float getSurcharge();

    /**
     * <code>required float mta_tax = 14;</code>
     */
    boolean hasMtaTax();
    /**
     * <code>required float mta_tax = 14;</code>
     */
    float getMtaTax();

    /**
     * <code>required float tip_amount = 15;</code>
     */
    boolean hasTipAmount();
    /**
     * <code>required float tip_amount = 15;</code>
     */
    float getTipAmount();

    /**
     * <code>required float tolls_amount = 16;</code>
     */
    boolean hasTollsAmount();
    /**
     * <code>required float tolls_amount = 16;</code>
     */
    float getTollsAmount();

    /**
     * <code>required float total_amount = 17;</code>
     */
    boolean hasTotalAmount();
    /**
     * <code>required float total_amount = 17;</code>
     */
    float getTotalAmount();
  }
  /**
   * Protobuf type {@code pb.Taxitrip}
   */
  public static final class Taxitrip extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:pb.Taxitrip)
      TaxitripOrBuilder {
    // Use Taxitrip.newBuilder() to construct.
    private Taxitrip(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Taxitrip(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Taxitrip defaultInstance;
    public static Taxitrip getDefaultInstance() {
      return defaultInstance;
    }

    public Taxitrip getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Taxitrip(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              medallion_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              hackLicense_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              pickupDatetime_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              dropoffDatetime_ = bs;
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              tripTimeInSecs_ = input.readUInt32();
              break;
            }
            case 53: {
              bitField0_ |= 0x00000020;
              tripDistance_ = input.readFloat();
              break;
            }
            case 61: {
              bitField0_ |= 0x00000040;
              pickupLongitude_ = input.readFloat();
              break;
            }
            case 69: {
              bitField0_ |= 0x00000080;
              pickupLatitude_ = input.readFloat();
              break;
            }
            case 77: {
              bitField0_ |= 0x00000100;
              dropoffLongitude_ = input.readFloat();
              break;
            }
            case 85: {
              bitField0_ |= 0x00000200;
              dropoffLatitude_ = input.readFloat();
              break;
            }
            case 90: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000400;
              paymentType_ = bs;
              break;
            }
            case 101: {
              bitField0_ |= 0x00000800;
              fareAmount_ = input.readFloat();
              break;
            }
            case 109: {
              bitField0_ |= 0x00001000;
              surcharge_ = input.readFloat();
              break;
            }
            case 117: {
              bitField0_ |= 0x00002000;
              mtaTax_ = input.readFloat();
              break;
            }
            case 125: {
              bitField0_ |= 0x00004000;
              tipAmount_ = input.readFloat();
              break;
            }
            case 133: {
              bitField0_ |= 0x00008000;
              tollsAmount_ = input.readFloat();
              break;
            }
            case 141: {
              bitField0_ |= 0x00010000;
              totalAmount_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.tum.i13.pb.Debs2015Protos.internal_static_pb_Taxitrip_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.tum.i13.pb.Debs2015Protos.internal_static_pb_Taxitrip_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.tum.i13.pb.Debs2015Protos.Taxitrip.class, de.tum.i13.pb.Debs2015Protos.Taxitrip.Builder.class);
    }

    public static com.google.protobuf.Parser<Taxitrip> PARSER =
        new com.google.protobuf.AbstractParser<Taxitrip>() {
      public Taxitrip parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Taxitrip(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Taxitrip> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int MEDALLION_FIELD_NUMBER = 1;
    private java.lang.Object medallion_;
    /**
     * <code>required string medallion = 1;</code>
     */
    public boolean hasMedallion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string medallion = 1;</code>
     */
    public java.lang.String getMedallion() {
      java.lang.Object ref = medallion_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          medallion_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string medallion = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMedallionBytes() {
      java.lang.Object ref = medallion_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        medallion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HACK_LICENSE_FIELD_NUMBER = 2;
    private java.lang.Object hackLicense_;
    /**
     * <code>required string hack_license = 2;</code>
     */
    public boolean hasHackLicense() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string hack_license = 2;</code>
     */
    public java.lang.String getHackLicense() {
      java.lang.Object ref = hackLicense_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          hackLicense_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string hack_license = 2;</code>
     */
    public com.google.protobuf.ByteString
        getHackLicenseBytes() {
      java.lang.Object ref = hackLicense_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hackLicense_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PICKUP_DATETIME_FIELD_NUMBER = 3;
    private java.lang.Object pickupDatetime_;
    /**
     * <code>required string pickup_datetime = 3;</code>
     */
    public boolean hasPickupDatetime() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string pickup_datetime = 3;</code>
     */
    public java.lang.String getPickupDatetime() {
      java.lang.Object ref = pickupDatetime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          pickupDatetime_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string pickup_datetime = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPickupDatetimeBytes() {
      java.lang.Object ref = pickupDatetime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pickupDatetime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DROPOFF_DATETIME_FIELD_NUMBER = 4;
    private java.lang.Object dropoffDatetime_;
    /**
     * <code>required string dropoff_datetime = 4;</code>
     */
    public boolean hasDropoffDatetime() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string dropoff_datetime = 4;</code>
     */
    public java.lang.String getDropoffDatetime() {
      java.lang.Object ref = dropoffDatetime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          dropoffDatetime_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string dropoff_datetime = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDropoffDatetimeBytes() {
      java.lang.Object ref = dropoffDatetime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dropoffDatetime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TRIP_TIME_IN_SECS_FIELD_NUMBER = 5;
    private int tripTimeInSecs_;
    /**
     * <code>required uint32 trip_time_in_secs = 5;</code>
     */
    public boolean hasTripTimeInSecs() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required uint32 trip_time_in_secs = 5;</code>
     */
    public int getTripTimeInSecs() {
      return tripTimeInSecs_;
    }

    public static final int TRIP_DISTANCE_FIELD_NUMBER = 6;
    private float tripDistance_;
    /**
     * <code>required float trip_distance = 6;</code>
     */
    public boolean hasTripDistance() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required float trip_distance = 6;</code>
     */
    public float getTripDistance() {
      return tripDistance_;
    }

    public static final int PICKUP_LONGITUDE_FIELD_NUMBER = 7;
    private float pickupLongitude_;
    /**
     * <code>required float pickup_longitude = 7;</code>
     */
    public boolean hasPickupLongitude() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required float pickup_longitude = 7;</code>
     */
    public float getPickupLongitude() {
      return pickupLongitude_;
    }

    public static final int PICKUP_LATITUDE_FIELD_NUMBER = 8;
    private float pickupLatitude_;
    /**
     * <code>required float pickup_latitude = 8;</code>
     */
    public boolean hasPickupLatitude() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required float pickup_latitude = 8;</code>
     */
    public float getPickupLatitude() {
      return pickupLatitude_;
    }

    public static final int DROPOFF_LONGITUDE_FIELD_NUMBER = 9;
    private float dropoffLongitude_;
    /**
     * <code>required float dropoff_longitude = 9;</code>
     */
    public boolean hasDropoffLongitude() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>required float dropoff_longitude = 9;</code>
     */
    public float getDropoffLongitude() {
      return dropoffLongitude_;
    }

    public static final int DROPOFF_LATITUDE_FIELD_NUMBER = 10;
    private float dropoffLatitude_;
    /**
     * <code>required float dropoff_latitude = 10;</code>
     */
    public boolean hasDropoffLatitude() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>required float dropoff_latitude = 10;</code>
     */
    public float getDropoffLatitude() {
      return dropoffLatitude_;
    }

    public static final int PAYMENT_TYPE_FIELD_NUMBER = 11;
    private java.lang.Object paymentType_;
    /**
     * <code>required string payment_type = 11;</code>
     */
    public boolean hasPaymentType() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>required string payment_type = 11;</code>
     */
    public java.lang.String getPaymentType() {
      java.lang.Object ref = paymentType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          paymentType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string payment_type = 11;</code>
     */
    public com.google.protobuf.ByteString
        getPaymentTypeBytes() {
      java.lang.Object ref = paymentType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        paymentType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FARE_AMOUNT_FIELD_NUMBER = 12;
    private float fareAmount_;
    /**
     * <code>required float fare_amount = 12;</code>
     */
    public boolean hasFareAmount() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>required float fare_amount = 12;</code>
     */
    public float getFareAmount() {
      return fareAmount_;
    }

    public static final int SURCHARGE_FIELD_NUMBER = 13;
    private float surcharge_;
    /**
     * <code>required float surcharge = 13;</code>
     */
    public boolean hasSurcharge() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>required float surcharge = 13;</code>
     */
    public float getSurcharge() {
      return surcharge_;
    }

    public static final int MTA_TAX_FIELD_NUMBER = 14;
    private float mtaTax_;
    /**
     * <code>required float mta_tax = 14;</code>
     */
    public boolean hasMtaTax() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    /**
     * <code>required float mta_tax = 14;</code>
     */
    public float getMtaTax() {
      return mtaTax_;
    }

    public static final int TIP_AMOUNT_FIELD_NUMBER = 15;
    private float tipAmount_;
    /**
     * <code>required float tip_amount = 15;</code>
     */
    public boolean hasTipAmount() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    /**
     * <code>required float tip_amount = 15;</code>
     */
    public float getTipAmount() {
      return tipAmount_;
    }

    public static final int TOLLS_AMOUNT_FIELD_NUMBER = 16;
    private float tollsAmount_;
    /**
     * <code>required float tolls_amount = 16;</code>
     */
    public boolean hasTollsAmount() {
      return ((bitField0_ & 0x00008000) == 0x00008000);
    }
    /**
     * <code>required float tolls_amount = 16;</code>
     */
    public float getTollsAmount() {
      return tollsAmount_;
    }

    public static final int TOTAL_AMOUNT_FIELD_NUMBER = 17;
    private float totalAmount_;
    /**
     * <code>required float total_amount = 17;</code>
     */
    public boolean hasTotalAmount() {
      return ((bitField0_ & 0x00010000) == 0x00010000);
    }
    /**
     * <code>required float total_amount = 17;</code>
     */
    public float getTotalAmount() {
      return totalAmount_;
    }

    private void initFields() {
      medallion_ = "";
      hackLicense_ = "";
      pickupDatetime_ = "";
      dropoffDatetime_ = "";
      tripTimeInSecs_ = 0;
      tripDistance_ = 0F;
      pickupLongitude_ = 0F;
      pickupLatitude_ = 0F;
      dropoffLongitude_ = 0F;
      dropoffLatitude_ = 0F;
      paymentType_ = "";
      fareAmount_ = 0F;
      surcharge_ = 0F;
      mtaTax_ = 0F;
      tipAmount_ = 0F;
      tollsAmount_ = 0F;
      totalAmount_ = 0F;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMedallion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHackLicense()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPickupDatetime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDropoffDatetime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTripTimeInSecs()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTripDistance()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPickupLongitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPickupLatitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDropoffLongitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDropoffLatitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPaymentType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFareAmount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSurcharge()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMtaTax()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTipAmount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTollsAmount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTotalAmount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getMedallionBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getHackLicenseBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getPickupDatetimeBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getDropoffDatetimeBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt32(5, tripTimeInSecs_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeFloat(6, tripDistance_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeFloat(7, pickupLongitude_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeFloat(8, pickupLatitude_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeFloat(9, dropoffLongitude_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeFloat(10, dropoffLatitude_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeBytes(11, getPaymentTypeBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeFloat(12, fareAmount_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeFloat(13, surcharge_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeFloat(14, mtaTax_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        output.writeFloat(15, tipAmount_);
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        output.writeFloat(16, tollsAmount_);
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        output.writeFloat(17, totalAmount_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getMedallionBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getHackLicenseBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getPickupDatetimeBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getDropoffDatetimeBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, tripTimeInSecs_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(6, tripDistance_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(7, pickupLongitude_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(8, pickupLatitude_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(9, dropoffLongitude_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(10, dropoffLatitude_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, getPaymentTypeBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(12, fareAmount_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(13, surcharge_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(14, mtaTax_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(15, tipAmount_);
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(16, tollsAmount_);
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(17, totalAmount_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static de.tum.i13.pb.Debs2015Protos.Taxitrip parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.tum.i13.pb.Debs2015Protos.Taxitrip parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.tum.i13.pb.Debs2015Protos.Taxitrip parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.tum.i13.pb.Debs2015Protos.Taxitrip parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.tum.i13.pb.Debs2015Protos.Taxitrip parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static de.tum.i13.pb.Debs2015Protos.Taxitrip parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static de.tum.i13.pb.Debs2015Protos.Taxitrip parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static de.tum.i13.pb.Debs2015Protos.Taxitrip parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static de.tum.i13.pb.Debs2015Protos.Taxitrip parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static de.tum.i13.pb.Debs2015Protos.Taxitrip parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(de.tum.i13.pb.Debs2015Protos.Taxitrip prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pb.Taxitrip}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pb.Taxitrip)
        de.tum.i13.pb.Debs2015Protos.TaxitripOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.tum.i13.pb.Debs2015Protos.internal_static_pb_Taxitrip_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.tum.i13.pb.Debs2015Protos.internal_static_pb_Taxitrip_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                de.tum.i13.pb.Debs2015Protos.Taxitrip.class, de.tum.i13.pb.Debs2015Protos.Taxitrip.Builder.class);
      }

      // Construct using de.tum.i13.pb.Debs2015Protos.Taxitrip.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        medallion_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        hackLicense_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        pickupDatetime_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        dropoffDatetime_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        tripTimeInSecs_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        tripDistance_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000020);
        pickupLongitude_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000040);
        pickupLatitude_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000080);
        dropoffLongitude_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000100);
        dropoffLatitude_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000200);
        paymentType_ = "";
        bitField0_ = (bitField0_ & ~0x00000400);
        fareAmount_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000800);
        surcharge_ = 0F;
        bitField0_ = (bitField0_ & ~0x00001000);
        mtaTax_ = 0F;
        bitField0_ = (bitField0_ & ~0x00002000);
        tipAmount_ = 0F;
        bitField0_ = (bitField0_ & ~0x00004000);
        tollsAmount_ = 0F;
        bitField0_ = (bitField0_ & ~0x00008000);
        totalAmount_ = 0F;
        bitField0_ = (bitField0_ & ~0x00010000);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.tum.i13.pb.Debs2015Protos.internal_static_pb_Taxitrip_descriptor;
      }

      public de.tum.i13.pb.Debs2015Protos.Taxitrip getDefaultInstanceForType() {
        return de.tum.i13.pb.Debs2015Protos.Taxitrip.getDefaultInstance();
      }

      public de.tum.i13.pb.Debs2015Protos.Taxitrip build() {
        de.tum.i13.pb.Debs2015Protos.Taxitrip result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public de.tum.i13.pb.Debs2015Protos.Taxitrip buildPartial() {
        de.tum.i13.pb.Debs2015Protos.Taxitrip result = new de.tum.i13.pb.Debs2015Protos.Taxitrip(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.medallion_ = medallion_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.hackLicense_ = hackLicense_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.pickupDatetime_ = pickupDatetime_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.dropoffDatetime_ = dropoffDatetime_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.tripTimeInSecs_ = tripTimeInSecs_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.tripDistance_ = tripDistance_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.pickupLongitude_ = pickupLongitude_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.pickupLatitude_ = pickupLatitude_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.dropoffLongitude_ = dropoffLongitude_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.dropoffLatitude_ = dropoffLatitude_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.paymentType_ = paymentType_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.fareAmount_ = fareAmount_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.surcharge_ = surcharge_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.mtaTax_ = mtaTax_;
        if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
          to_bitField0_ |= 0x00004000;
        }
        result.tipAmount_ = tipAmount_;
        if (((from_bitField0_ & 0x00008000) == 0x00008000)) {
          to_bitField0_ |= 0x00008000;
        }
        result.tollsAmount_ = tollsAmount_;
        if (((from_bitField0_ & 0x00010000) == 0x00010000)) {
          to_bitField0_ |= 0x00010000;
        }
        result.totalAmount_ = totalAmount_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.tum.i13.pb.Debs2015Protos.Taxitrip) {
          return mergeFrom((de.tum.i13.pb.Debs2015Protos.Taxitrip)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(de.tum.i13.pb.Debs2015Protos.Taxitrip other) {
        if (other == de.tum.i13.pb.Debs2015Protos.Taxitrip.getDefaultInstance()) return this;
        if (other.hasMedallion()) {
          bitField0_ |= 0x00000001;
          medallion_ = other.medallion_;
          onChanged();
        }
        if (other.hasHackLicense()) {
          bitField0_ |= 0x00000002;
          hackLicense_ = other.hackLicense_;
          onChanged();
        }
        if (other.hasPickupDatetime()) {
          bitField0_ |= 0x00000004;
          pickupDatetime_ = other.pickupDatetime_;
          onChanged();
        }
        if (other.hasDropoffDatetime()) {
          bitField0_ |= 0x00000008;
          dropoffDatetime_ = other.dropoffDatetime_;
          onChanged();
        }
        if (other.hasTripTimeInSecs()) {
          setTripTimeInSecs(other.getTripTimeInSecs());
        }
        if (other.hasTripDistance()) {
          setTripDistance(other.getTripDistance());
        }
        if (other.hasPickupLongitude()) {
          setPickupLongitude(other.getPickupLongitude());
        }
        if (other.hasPickupLatitude()) {
          setPickupLatitude(other.getPickupLatitude());
        }
        if (other.hasDropoffLongitude()) {
          setDropoffLongitude(other.getDropoffLongitude());
        }
        if (other.hasDropoffLatitude()) {
          setDropoffLatitude(other.getDropoffLatitude());
        }
        if (other.hasPaymentType()) {
          bitField0_ |= 0x00000400;
          paymentType_ = other.paymentType_;
          onChanged();
        }
        if (other.hasFareAmount()) {
          setFareAmount(other.getFareAmount());
        }
        if (other.hasSurcharge()) {
          setSurcharge(other.getSurcharge());
        }
        if (other.hasMtaTax()) {
          setMtaTax(other.getMtaTax());
        }
        if (other.hasTipAmount()) {
          setTipAmount(other.getTipAmount());
        }
        if (other.hasTollsAmount()) {
          setTollsAmount(other.getTollsAmount());
        }
        if (other.hasTotalAmount()) {
          setTotalAmount(other.getTotalAmount());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMedallion()) {
          
          return false;
        }
        if (!hasHackLicense()) {
          
          return false;
        }
        if (!hasPickupDatetime()) {
          
          return false;
        }
        if (!hasDropoffDatetime()) {
          
          return false;
        }
        if (!hasTripTimeInSecs()) {
          
          return false;
        }
        if (!hasTripDistance()) {
          
          return false;
        }
        if (!hasPickupLongitude()) {
          
          return false;
        }
        if (!hasPickupLatitude()) {
          
          return false;
        }
        if (!hasDropoffLongitude()) {
          
          return false;
        }
        if (!hasDropoffLatitude()) {
          
          return false;
        }
        if (!hasPaymentType()) {
          
          return false;
        }
        if (!hasFareAmount()) {
          
          return false;
        }
        if (!hasSurcharge()) {
          
          return false;
        }
        if (!hasMtaTax()) {
          
          return false;
        }
        if (!hasTipAmount()) {
          
          return false;
        }
        if (!hasTollsAmount()) {
          
          return false;
        }
        if (!hasTotalAmount()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        de.tum.i13.pb.Debs2015Protos.Taxitrip parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (de.tum.i13.pb.Debs2015Protos.Taxitrip) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object medallion_ = "";
      /**
       * <code>required string medallion = 1;</code>
       */
      public boolean hasMedallion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string medallion = 1;</code>
       */
      public java.lang.String getMedallion() {
        java.lang.Object ref = medallion_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            medallion_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string medallion = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMedallionBytes() {
        java.lang.Object ref = medallion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          medallion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string medallion = 1;</code>
       */
      public Builder setMedallion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        medallion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string medallion = 1;</code>
       */
      public Builder clearMedallion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        medallion_ = getDefaultInstance().getMedallion();
        onChanged();
        return this;
      }
      /**
       * <code>required string medallion = 1;</code>
       */
      public Builder setMedallionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        medallion_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object hackLicense_ = "";
      /**
       * <code>required string hack_license = 2;</code>
       */
      public boolean hasHackLicense() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string hack_license = 2;</code>
       */
      public java.lang.String getHackLicense() {
        java.lang.Object ref = hackLicense_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            hackLicense_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string hack_license = 2;</code>
       */
      public com.google.protobuf.ByteString
          getHackLicenseBytes() {
        java.lang.Object ref = hackLicense_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hackLicense_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string hack_license = 2;</code>
       */
      public Builder setHackLicense(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        hackLicense_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string hack_license = 2;</code>
       */
      public Builder clearHackLicense() {
        bitField0_ = (bitField0_ & ~0x00000002);
        hackLicense_ = getDefaultInstance().getHackLicense();
        onChanged();
        return this;
      }
      /**
       * <code>required string hack_license = 2;</code>
       */
      public Builder setHackLicenseBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        hackLicense_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object pickupDatetime_ = "";
      /**
       * <code>required string pickup_datetime = 3;</code>
       */
      public boolean hasPickupDatetime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string pickup_datetime = 3;</code>
       */
      public java.lang.String getPickupDatetime() {
        java.lang.Object ref = pickupDatetime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            pickupDatetime_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string pickup_datetime = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPickupDatetimeBytes() {
        java.lang.Object ref = pickupDatetime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pickupDatetime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string pickup_datetime = 3;</code>
       */
      public Builder setPickupDatetime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        pickupDatetime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string pickup_datetime = 3;</code>
       */
      public Builder clearPickupDatetime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        pickupDatetime_ = getDefaultInstance().getPickupDatetime();
        onChanged();
        return this;
      }
      /**
       * <code>required string pickup_datetime = 3;</code>
       */
      public Builder setPickupDatetimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        pickupDatetime_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object dropoffDatetime_ = "";
      /**
       * <code>required string dropoff_datetime = 4;</code>
       */
      public boolean hasDropoffDatetime() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string dropoff_datetime = 4;</code>
       */
      public java.lang.String getDropoffDatetime() {
        java.lang.Object ref = dropoffDatetime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            dropoffDatetime_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string dropoff_datetime = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDropoffDatetimeBytes() {
        java.lang.Object ref = dropoffDatetime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dropoffDatetime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string dropoff_datetime = 4;</code>
       */
      public Builder setDropoffDatetime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        dropoffDatetime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string dropoff_datetime = 4;</code>
       */
      public Builder clearDropoffDatetime() {
        bitField0_ = (bitField0_ & ~0x00000008);
        dropoffDatetime_ = getDefaultInstance().getDropoffDatetime();
        onChanged();
        return this;
      }
      /**
       * <code>required string dropoff_datetime = 4;</code>
       */
      public Builder setDropoffDatetimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        dropoffDatetime_ = value;
        onChanged();
        return this;
      }

      private int tripTimeInSecs_ ;
      /**
       * <code>required uint32 trip_time_in_secs = 5;</code>
       */
      public boolean hasTripTimeInSecs() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required uint32 trip_time_in_secs = 5;</code>
       */
      public int getTripTimeInSecs() {
        return tripTimeInSecs_;
      }
      /**
       * <code>required uint32 trip_time_in_secs = 5;</code>
       */
      public Builder setTripTimeInSecs(int value) {
        bitField0_ |= 0x00000010;
        tripTimeInSecs_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 trip_time_in_secs = 5;</code>
       */
      public Builder clearTripTimeInSecs() {
        bitField0_ = (bitField0_ & ~0x00000010);
        tripTimeInSecs_ = 0;
        onChanged();
        return this;
      }

      private float tripDistance_ ;
      /**
       * <code>required float trip_distance = 6;</code>
       */
      public boolean hasTripDistance() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required float trip_distance = 6;</code>
       */
      public float getTripDistance() {
        return tripDistance_;
      }
      /**
       * <code>required float trip_distance = 6;</code>
       */
      public Builder setTripDistance(float value) {
        bitField0_ |= 0x00000020;
        tripDistance_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float trip_distance = 6;</code>
       */
      public Builder clearTripDistance() {
        bitField0_ = (bitField0_ & ~0x00000020);
        tripDistance_ = 0F;
        onChanged();
        return this;
      }

      private float pickupLongitude_ ;
      /**
       * <code>required float pickup_longitude = 7;</code>
       */
      public boolean hasPickupLongitude() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required float pickup_longitude = 7;</code>
       */
      public float getPickupLongitude() {
        return pickupLongitude_;
      }
      /**
       * <code>required float pickup_longitude = 7;</code>
       */
      public Builder setPickupLongitude(float value) {
        bitField0_ |= 0x00000040;
        pickupLongitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float pickup_longitude = 7;</code>
       */
      public Builder clearPickupLongitude() {
        bitField0_ = (bitField0_ & ~0x00000040);
        pickupLongitude_ = 0F;
        onChanged();
        return this;
      }

      private float pickupLatitude_ ;
      /**
       * <code>required float pickup_latitude = 8;</code>
       */
      public boolean hasPickupLatitude() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required float pickup_latitude = 8;</code>
       */
      public float getPickupLatitude() {
        return pickupLatitude_;
      }
      /**
       * <code>required float pickup_latitude = 8;</code>
       */
      public Builder setPickupLatitude(float value) {
        bitField0_ |= 0x00000080;
        pickupLatitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float pickup_latitude = 8;</code>
       */
      public Builder clearPickupLatitude() {
        bitField0_ = (bitField0_ & ~0x00000080);
        pickupLatitude_ = 0F;
        onChanged();
        return this;
      }

      private float dropoffLongitude_ ;
      /**
       * <code>required float dropoff_longitude = 9;</code>
       */
      public boolean hasDropoffLongitude() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>required float dropoff_longitude = 9;</code>
       */
      public float getDropoffLongitude() {
        return dropoffLongitude_;
      }
      /**
       * <code>required float dropoff_longitude = 9;</code>
       */
      public Builder setDropoffLongitude(float value) {
        bitField0_ |= 0x00000100;
        dropoffLongitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float dropoff_longitude = 9;</code>
       */
      public Builder clearDropoffLongitude() {
        bitField0_ = (bitField0_ & ~0x00000100);
        dropoffLongitude_ = 0F;
        onChanged();
        return this;
      }

      private float dropoffLatitude_ ;
      /**
       * <code>required float dropoff_latitude = 10;</code>
       */
      public boolean hasDropoffLatitude() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>required float dropoff_latitude = 10;</code>
       */
      public float getDropoffLatitude() {
        return dropoffLatitude_;
      }
      /**
       * <code>required float dropoff_latitude = 10;</code>
       */
      public Builder setDropoffLatitude(float value) {
        bitField0_ |= 0x00000200;
        dropoffLatitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float dropoff_latitude = 10;</code>
       */
      public Builder clearDropoffLatitude() {
        bitField0_ = (bitField0_ & ~0x00000200);
        dropoffLatitude_ = 0F;
        onChanged();
        return this;
      }

      private java.lang.Object paymentType_ = "";
      /**
       * <code>required string payment_type = 11;</code>
       */
      public boolean hasPaymentType() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>required string payment_type = 11;</code>
       */
      public java.lang.String getPaymentType() {
        java.lang.Object ref = paymentType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            paymentType_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string payment_type = 11;</code>
       */
      public com.google.protobuf.ByteString
          getPaymentTypeBytes() {
        java.lang.Object ref = paymentType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          paymentType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string payment_type = 11;</code>
       */
      public Builder setPaymentType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        paymentType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string payment_type = 11;</code>
       */
      public Builder clearPaymentType() {
        bitField0_ = (bitField0_ & ~0x00000400);
        paymentType_ = getDefaultInstance().getPaymentType();
        onChanged();
        return this;
      }
      /**
       * <code>required string payment_type = 11;</code>
       */
      public Builder setPaymentTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        paymentType_ = value;
        onChanged();
        return this;
      }

      private float fareAmount_ ;
      /**
       * <code>required float fare_amount = 12;</code>
       */
      public boolean hasFareAmount() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>required float fare_amount = 12;</code>
       */
      public float getFareAmount() {
        return fareAmount_;
      }
      /**
       * <code>required float fare_amount = 12;</code>
       */
      public Builder setFareAmount(float value) {
        bitField0_ |= 0x00000800;
        fareAmount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float fare_amount = 12;</code>
       */
      public Builder clearFareAmount() {
        bitField0_ = (bitField0_ & ~0x00000800);
        fareAmount_ = 0F;
        onChanged();
        return this;
      }

      private float surcharge_ ;
      /**
       * <code>required float surcharge = 13;</code>
       */
      public boolean hasSurcharge() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>required float surcharge = 13;</code>
       */
      public float getSurcharge() {
        return surcharge_;
      }
      /**
       * <code>required float surcharge = 13;</code>
       */
      public Builder setSurcharge(float value) {
        bitField0_ |= 0x00001000;
        surcharge_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float surcharge = 13;</code>
       */
      public Builder clearSurcharge() {
        bitField0_ = (bitField0_ & ~0x00001000);
        surcharge_ = 0F;
        onChanged();
        return this;
      }

      private float mtaTax_ ;
      /**
       * <code>required float mta_tax = 14;</code>
       */
      public boolean hasMtaTax() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      /**
       * <code>required float mta_tax = 14;</code>
       */
      public float getMtaTax() {
        return mtaTax_;
      }
      /**
       * <code>required float mta_tax = 14;</code>
       */
      public Builder setMtaTax(float value) {
        bitField0_ |= 0x00002000;
        mtaTax_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float mta_tax = 14;</code>
       */
      public Builder clearMtaTax() {
        bitField0_ = (bitField0_ & ~0x00002000);
        mtaTax_ = 0F;
        onChanged();
        return this;
      }

      private float tipAmount_ ;
      /**
       * <code>required float tip_amount = 15;</code>
       */
      public boolean hasTipAmount() {
        return ((bitField0_ & 0x00004000) == 0x00004000);
      }
      /**
       * <code>required float tip_amount = 15;</code>
       */
      public float getTipAmount() {
        return tipAmount_;
      }
      /**
       * <code>required float tip_amount = 15;</code>
       */
      public Builder setTipAmount(float value) {
        bitField0_ |= 0x00004000;
        tipAmount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float tip_amount = 15;</code>
       */
      public Builder clearTipAmount() {
        bitField0_ = (bitField0_ & ~0x00004000);
        tipAmount_ = 0F;
        onChanged();
        return this;
      }

      private float tollsAmount_ ;
      /**
       * <code>required float tolls_amount = 16;</code>
       */
      public boolean hasTollsAmount() {
        return ((bitField0_ & 0x00008000) == 0x00008000);
      }
      /**
       * <code>required float tolls_amount = 16;</code>
       */
      public float getTollsAmount() {
        return tollsAmount_;
      }
      /**
       * <code>required float tolls_amount = 16;</code>
       */
      public Builder setTollsAmount(float value) {
        bitField0_ |= 0x00008000;
        tollsAmount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float tolls_amount = 16;</code>
       */
      public Builder clearTollsAmount() {
        bitField0_ = (bitField0_ & ~0x00008000);
        tollsAmount_ = 0F;
        onChanged();
        return this;
      }

      private float totalAmount_ ;
      /**
       * <code>required float total_amount = 17;</code>
       */
      public boolean hasTotalAmount() {
        return ((bitField0_ & 0x00010000) == 0x00010000);
      }
      /**
       * <code>required float total_amount = 17;</code>
       */
      public float getTotalAmount() {
        return totalAmount_;
      }
      /**
       * <code>required float total_amount = 17;</code>
       */
      public Builder setTotalAmount(float value) {
        bitField0_ |= 0x00010000;
        totalAmount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float total_amount = 17;</code>
       */
      public Builder clearTotalAmount() {
        bitField0_ = (bitField0_ & ~0x00010000);
        totalAmount_ = 0F;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pb.Taxitrip)
    }

    static {
      defaultInstance = new Taxitrip(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:pb.Taxitrip)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_Taxitrip_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pb_Taxitrip_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016debs2015.proto\022\002pb\"\217\003\n\010Taxitrip\022\021\n\tmed" +
      "allion\030\001 \002(\t\022\024\n\014hack_license\030\002 \002(\t\022\027\n\017pi" +
      "ckup_datetime\030\003 \002(\t\022\030\n\020dropoff_datetime\030" +
      "\004 \002(\t\022\031\n\021trip_time_in_secs\030\005 \002(\r\022\025\n\rtrip" +
      "_distance\030\006 \002(\002\022\030\n\020pickup_longitude\030\007 \002(" +
      "\002\022\027\n\017pickup_latitude\030\010 \002(\002\022\031\n\021dropoff_lo" +
      "ngitude\030\t \002(\002\022\030\n\020dropoff_latitude\030\n \002(\002\022" +
      "\024\n\014payment_type\030\013 \002(\t\022\023\n\013fare_amount\030\014 \002" +
      "(\002\022\021\n\tsurcharge\030\r \002(\002\022\017\n\007mta_tax\030\016 \002(\002\022\022" +
      "\n\ntip_amount\030\017 \002(\002\022\024\n\014tolls_amount\030\020 \002(\002",
      "\022\024\n\014total_amount\030\021 \002(\002B\037\n\rde.tum.i13.pbB" +
      "\016Debs2015Protos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_pb_Taxitrip_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pb_Taxitrip_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_pb_Taxitrip_descriptor,
        new java.lang.String[] { "Medallion", "HackLicense", "PickupDatetime", "DropoffDatetime", "TripTimeInSecs", "TripDistance", "PickupLongitude", "PickupLatitude", "DropoffLongitude", "DropoffLatitude", "PaymentType", "FareAmount", "Surcharge", "MtaTax", "TipAmount", "TollsAmount", "TotalAmount", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
